# Generated by Django 5.2.1 on 2025-05-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ф.И.О')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание мероприятия')),
                ('start_event', models.DateTimeField(blank=True, null=True, verbose_name='Начало мероприятия')),
                ('end_event', models.DateTimeField(blank=True, null=True, verbose_name='Конец мероприятия')),
                ('speakers', models.ManyToManyField(related_name='events', to='events.speaker', verbose_name='Докладчики')),
            ],
        ),
    ]
