# Generated by Django 5.2.1 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="telegram_id",
            field=models.BigIntegerField(verbose_name="Telegram ID"),
        ),
    ]
