# Generated by Django 5.2.1 on 2025-05-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakertalk',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активное выступление'),
        ),
    ]
