# Generated by Django 5.2.1 on 2025-05-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_speakertalk_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakertalk',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Тема доклада'),
        ),
    ]
