# Generated by Django 5.2.1 on 2026-07-18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("events", "0002_alter_speaker_telegram_id")]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payload", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("telegram_id", models.BigIntegerField()),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("status", models.CharField(choices=[("pending", "Ожидает оплаты"), ("paid", "Оплачен")], default="pending", max_length=10)),
                ("telegram_payment_charge_id", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("donation", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="events.donate")),
            ],
        ),
    ]
