# Generated by Django 5.2.1 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("events", "0003_payment")]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="telegram_id",
            field=models.BigIntegerField(unique=True, verbose_name="Telegram ID"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="telegram_id",
            field=models.BigIntegerField(unique=True, verbose_name="Telegram ID"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name="Telegram ID"),
        ),
    ]
