# Generated by Django 5.2.1 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("events", "0004_alter_speaker_telegram_id_and_more")]

    operations = [
        migrations.AddField(
            model_name="sendmessage",
            name="delivered_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Доставлено"),
        ),
        migrations.AddField(
            model_name="sendmessage",
            name="failed_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Ошибки доставки"),
        ),
    ]
