# Generated by Django 5.2.1 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("events", "0005_sendmessage_delivery_counts")]

    operations = [
        migrations.CreateModel(
            name="BotUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("telegram_id", models.BigIntegerField(unique=True, verbose_name="Telegram ID")),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={"verbose_name": "Пользователь бота", "verbose_name_plural": "Пользователи бота"},
        ),
    ]
