# Generated by Django 5.2.1 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_botuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает отправки"),
                            ("sent", "Доставлено"),
                            ("failed", "Ошибка доставки"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="events.sendmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доставка рассылки",
                "verbose_name_plural": "Доставки рассылок",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("broadcast", "telegram_id"),
                        name="unique_broadcast_recipient",
                    )
                ],
            },
        ),
    ]
